version: '3.8'

services:
  web:
    build: .
    restart: always
    volumes:
      - .:/app
      - static_volume:/app/static
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=your-secret-key-here
      - DJANGO_SETTINGS_MODULE=basen.settings
    command: >
      bash -c "python manage.py compilemessages &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"

volumes:
  static_volume: